language: java
os: windows
jdk: openjdk11
jobs:
  include:
    - stage: "Build project"
      script:
        - ./gradlew build

deploy:
  provider: heroku
  app: dio-cities-api-2
  api_key: $HEROKU_KEY
